### ISSUE TITLE
你好，我想咨询一下问题

### ISSUE THREAD

**Issue by untilyou0715** [GaryDoooo/acer_e51_osx#1]
我的机型是e5-571g-515g，配置跟你差不多，只有网卡是不一样的，我通过别的方式解决了网卡问题，还有一个问题想咨询一下，我的笔记本屏幕是1080p的，现在显示正常 ，无花屏闪屏问题，但是但是字体太小了，改别的分辨率，屏幕变得很模糊。我用网上的教程开启hidpi之后，缩放别的分辨率，字体变大也挺清晰，但是会出现闪屏花屏问题，这个怎么解决呢？
还有就是想问一下，你还会更新这个项目吗

**Comment by GaryDoooo** [comment]
嗯。。。我这个是HD显示的所以没遇到过这样的问题。。。但愿我不会心血来潮再装一次黑苹果，搞一次太累了。

**Comment by untilyou0715** [comment]
闪屏这个问题我弄好了，但是睡眠还要风扇的问题好像是解决不了了

**Comment by GaryDoooo** [comment]
睡眠是玄学，GLHF。
